name: Renovate Config Validation
on:
  push:
    branches: [main]
    paths:
      - .github/renovate.json
      - .github/workflows/renovate-verify.yaml
  pull_request:
    branches: [main]
    paths:
      - .github/renovate.json
      - .github/workflows/renovate-verify.yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  validate:
    name: Validate Renovate Configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "latest"
      - name: Validate configuration
        run: npx --yes --package renovate renovate-config-validator .github/renovate.json
